### ISSUE TITLE
parsing error on CXF files with Gauss Boaga coordinate system (Z)

### ISSUE THREAD

**Issue by cbertelli** [bopen/bgeo.catasto#1]
Issuing a bug on CXF in English sounds funny, anyway...
There is a parsing error on the cxf file. The procedure expects a 0 or a U and the data say "Z".
This is the text of the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/cxf2ogr", line 11, in <module>
    sys.exit(main_cxf())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/bgeo/catasto/apps.py", line 22, in main_cxf
    foglio = cxf.parse_foglio(source)
  File "/usr/local/lib/python2.7/site-packages/bgeo/catasto/cxf.py", line 73, in parse_foglio
    assert foglio['CODICE SVILUPPO'] in ['0', 'U']
AssertionError

```

My file is called CXXX_006000Z.CXF, the Z denotes the change of coordinate system from Cassini-Soldner to Gauss Boaga. So, even adding Z to the possible options

`assert foglio['CODICE SVILUPPO'] in ['0', 'U', 'Z']`

the conversion fails on coordinates:

```
ERROR 1: latitude or longitude exceeded limits
ERROR 1: Reprojection failed, err = -14, further errors will be suppressed on the transform object.
corrections (0.0, 0.0) (0.0, 0.0)

```

(obviously the numbers are way bigger).
So it seems Gauss Boaga is not a possible option.

**Comment by alexamici** [comment]
You are right, Gauss-Boaga coordinates are not supported by the tool as it is. I remember I translated some Z file last time I used bgeo.catasto (a few years ago!) but probably by adding the call to the proj4 library by hand inside the code.

The feature request is legit, but FYI I don't plan to implement it any time soon.
